### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by nakajima** [clippyjs/clippy.js#1]
Can you add a license to this project please? Thanks!

**Comment by smore-inc** [comment]
We've added the MIT license :p

**Comment by nakajima** [comment]
Rad. Thanks!

**Comment by coderanger** [comment]
I know this is old, but do you know what the license on the actual agent images/sounds is?

**Comment by coderanger** [comment]
Some quick recon shows they are probably All Rights Reserved MS so while funny, probably not technically legal to redist these :(
