### ISSUE TITLE
Alternatives to Clippy JS

### ISSUE THREAD

**Issue by nunomaduro** [clippyjs/clippy.js#32]
Hey,

Your project is amazing, but I need a highly customisable library for kids games, so i would like to search for alternatives. Do you know any ?

Thanks.

**Comment by CosmicWebServices** [comment]
Well don't know of any but you can take a image sprite and do some animations even with a simple framework like [animate.css](https://daneden.github.io/animate.css/) you can as do [this](http://www.williammalone.com/articles/create-html5-canvas-javascript-sprite-animation/)! Good Luck!
