### ISSUE TITLE
How to pause the animation loop to keep the clippy character in a specific gesture

### ISSUE THREAD

**Issue by aziz** [clippyjs/clippy.js#5]
I'd like to make Melin look up and stay looking up until I tell him the next animation move, how can I accomplish such a thing?

**Comment by karlbright** [comment]
I wouldn't say opening an issue is the best place for this?

https://github.com/smore-inc/clippy.js/blob/master/src/animator.js and https://github.com/smore-inc/clippy.js/blob/master/src/agent.js are probably the best places to look at how you could do this. As far as I can tell this isn't part of the API of the agents.

That being said, this isn't really an issue is it?

**Comment by smore-inc** [comment]
agent.play("LookUp", 0)
....
agent.stopCurrent()

**Comment by aziz** [comment]
Does not work, cause you still need to wait for the current animation (look up) to reach its end state and then stop the animation

**Comment by smore-inc** [comment]
You have a callback for that:

``` javascript
agent.play("LookUp", 0, function() {
 console.log("We're now looking up!");
 });
```

**Comment by smore-inc** [comment]
Oh, I see what you mean. What you need to do is switch to the "LookDownBlink" animation once you've reached the LookDown state (via the callback):

``` javascript
function blinky() { agent.play("LookDownBlink", 0, blinky); }
agent.play("LookDown", 0, blinky);
```

and then end it with "LookDownReturn".
For some reason they didn't employ the single animation looping logic in these animations (as opposed to the adorable Links sleeping animation), but rather they separated them to 3 animations.

It would be better to make agent.js support this switching logic natively, though ;)

**Comment by taufardh** [comment]
Finally I found it... This is what I looking for.. Thanks 🎉
