### ISSUE TITLE
Clippy stuck at the bottom of my page

### ISSUE THREAD

**Issue by dxf** [clippyjs/clippy.js#50]
Case in point: https://daf.lol

**Comment by dxf** [comment]
Wait nvm

**Comment by dxf** [comment]
Welp. Still doesn't work.

I've tried everything. How the hell do I make it move? I've used the moveTo stuff but still no dice

**Comment by dxf** [comment]
I can see that the script makes a div that contains it (I can shift it up and down in chrome inspect element), but I don't see a way I can override it.

**Comment by dxf** [comment]
Never mind, it's an ancient script and I doubt anyone will see this.

**Comment by Plloi** [comment]
Ancient, yes, but i saw.

**Comment by dxf** [comment]
woke af 👀

---- On Tue, 31 Jul 2018 18:41:34 +0000 notifications@github.com wrote ----

Ancient, yes, but i saw.
